# Generated by Django 4.2.5 on 2023-10-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('single_rate', models.FloatField()),
                ('single_dc', models.FloatField()),
                ('double_rate', models.FloatField()),
                ('double_dc', models.FloatField()),
                ('box_rate', models.FloatField()),
                ('box_dc', models.FloatField()),
                ('super_rate', models.FloatField()),
                ('super_dc', models.FloatField()),
                ('first_prize', models.FloatField()),
                ('first_dc', models.FloatField()),
                ('second_prize', models.FloatField()),
                ('second_dc', models.FloatField()),
                ('third_prize', models.FloatField()),
                ('third_dc', models.FloatField()),
                ('fourth_prize', models.FloatField()),
                ('fourth_dc', models.FloatField()),
                ('fifth_prize', models.FloatField()),
                ('fifth_dc', models.FloatField()),
                ('guarantee_prize', models.FloatField()),
                ('guarantee_dc', models.FloatField()),
                ('box_first_prize', models.FloatField()),
                ('box_first_prize_dc', models.FloatField()),
                ('box_series_prize', models.FloatField()),
                ('box_series_dc', models.FloatField()),
                ('single1_prize', models.FloatField()),
                ('single1_dc', models.FloatField()),
                ('double2_prize', models.FloatField()),
                ('double2_dc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('game_time', models.TimeField()),
            ],
        ),
    ]
