# Generated by Django 4.2.7 on 2023-11-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockednumber',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
