# Generated by Django 4.2.7 on 2023-11-11 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_blockednumber_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockednumber',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.playtime'),
        ),
    ]
