# Generated by Django 4.2.5 on 2023-10-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_playtime_end_time_alter_playtime_game_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playtime',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='playtime',
            name='game_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='playtime',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
