# Generated by Django 4.2.5 on 2023-10-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_collectionreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionreport',
            name='time',
        ),
    ]
