# Generated by Django 4.2.5 on 2023-10-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_playtime_end_time_alter_playtime_game_time_and_more'),
        ('adminapp', '0003_remove_collectionreport_time'),
    ]

    operations = [
    ]
