# Generated by Django 4.2.5 on 2023-10-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_merge_20231027_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super', models.IntegerField(default=0)),
                ('box', models.IntegerField(default=0)),
                ('ab', models.IntegerField(default=0)),
                ('bc', models.IntegerField(default=0)),
                ('ac', models.IntegerField(default=0)),
                ('a', models.IntegerField(default=0)),
                ('b', models.IntegerField(default=0)),
                ('c', models.IntegerField(default=0)),
            ],
        ),
    ]
