# Generated by Django 4.2.5 on 2023-10-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_winning'),
    ]

    operations = [
        migrations.AddField(
            model_name='winning',
            name='bill',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
