# Generated by Django 4.2.5 on 2023-10-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_winning_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winning',
            name='count',
            field=models.IntegerField(),
        ),
    ]
