# Generated by Django 4.2.7 on 2023-12-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_winning_commission_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedgame',
            name='cleared',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
