# Generated by Django 4.2.7 on 2023-11-08 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0002_alter_agent_agent_name_alter_agent_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('LSK', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('d_amount', models.FloatField()),
                ('c_amount', models.FloatField()),
                ('combined', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AgentGameTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('LSK', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('d_amount', models.FloatField()),
                ('c_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DealerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('single_rate', models.FloatField()),
                ('single_dc', models.FloatField()),
                ('double_rate', models.FloatField()),
                ('double_dc', models.FloatField()),
                ('box_rate', models.FloatField()),
                ('box_dc', models.FloatField()),
                ('super_rate', models.FloatField()),
                ('super_dc', models.FloatField()),
                ('first_prize', models.FloatField()),
                ('first_dc', models.FloatField()),
                ('second_prize', models.FloatField()),
                ('second_dc', models.FloatField()),
                ('third_prize', models.FloatField()),
                ('third_dc', models.FloatField()),
                ('fourth_prize', models.FloatField()),
                ('fourth_dc', models.FloatField()),
                ('fifth_prize', models.FloatField()),
                ('fifth_dc', models.FloatField()),
                ('guarantee_prize', models.FloatField()),
                ('guarantee_dc', models.FloatField()),
                ('box_first_prize', models.FloatField()),
                ('box_first_prize_dc', models.FloatField()),
                ('box_series_prize', models.FloatField()),
                ('box_series_dc', models.FloatField()),
                ('single1_prize', models.FloatField()),
                ('single1_dc', models.FloatField()),
                ('double2_prize', models.FloatField()),
                ('double2_dc', models.FloatField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='DealerLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.FloatField()),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.agent')),
                ('checked_times', models.ManyToManyField(to='adminapp.playtime')),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='DealerCollectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_or_to', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_c_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_d_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_count', models.DecimalField(decimal_places=0, max_digits=10)),
                ('win_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent_games', models.ManyToManyField(to='agent.agentgame')),
            ],
        ),
    ]
