# Generated by Django 4.2.5 on 2023-10-22 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealer', '0001_initial'),
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0002_initial'),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerpackage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealerpackage',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.dealer'),
        ),
        migrations.AddField(
            model_name='bill',
            name='agent_games',
            field=models.ManyToManyField(to='agent.agentgame'),
        ),
        migrations.AddField(
            model_name='bill',
            name='dealer_games',
            field=models.ManyToManyField(to='dealer.dealergame'),
        ),
        migrations.AddField(
            model_name='bill',
            name='time_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.playtime'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentgametest',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.agent'),
        ),
        migrations.AddField(
            model_name='agentgametest',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.playtime'),
        ),
        migrations.AddField(
            model_name='agentgame',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.agent'),
        ),
        migrations.AddField(
            model_name='agentgame',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.playtime'),
        ),
    ]
