# Generated by Django 4.2.6 on 2023-11-03 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('website', '0002_alter_agent_agent_name_alter_agent_phone_number_and_more'),
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.FloatField()),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.agent')),
                ('checked_times', models.ManyToManyField(to='adminapp.playtime')),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.dealer')),
            ],
        ),
    ]
