# Generated by Django 4.2.5 on 2023-10-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentgame',
            name='number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agentgametest',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
