# Generated by Django 4.2.5 on 2023-10-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        ('adminapp', '0002_initial'),
        ('agent', '0003_alter_agentgame_number_alter_agentgametest_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.agent')),
                ('agent_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agentgame')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.playtime')),
            ],
        ),
    ]
