# Generated by Django 4.2.5 on 2023-10-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_dealercollectionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='win_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
