# Generated by Django 4.2.7 on 2023-11-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_bill_dealer_game_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total_c_amount_admin',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='total_count_admin',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='total_d_amount_admin',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='win_amount_admin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
