# Generated by Django 4.2.5 on 2023-10-17 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        ('agent', '0004_agentbill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentbill',
            old_name='time',
            new_name='time_id',
        ),
        migrations.RemoveField(
            model_name='agentbill',
            name='agent_game',
        ),
        migrations.AddField(
            model_name='agentbill',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentbill',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.agent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentbill',
            name='date',
            field=models.DateField(),
        ),
    ]
