# Generated by Django 4.2.7 on 2023-11-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_dealergametestadmin'),
        ('agent', '0004_bill_total_c_amount_admin_bill_total_count_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='dealer_game_admin',
        ),
        migrations.AddField(
            model_name='bill',
            name='dealer_game_admin',
            field=models.ManyToManyField(to='dealer.dealergameadmin'),
        ),
    ]
