# Generated by Django 4.2.7 on 2023-11-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_remove_bill_dealer_game_admin_bill_dealer_game_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='dealer_game_admin',
        ),
    ]
