# Generated by Django 4.2.7 on 2023-11-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_remove_bill_dealer_game_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='total_count_admin',
        ),
    ]
