# Generated by Django 4.2.7 on 2023-11-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_remove_bill_total_count_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total_c_amount_admin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_d_amount_admin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
