# Generated by Django 4.2.5 on 2023-10-19 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_delete_dealerbill'),
        ('agent', '0008_bill_delete_agentbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='agent_games',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agentgame'),
        ),
        migrations.AddField(
            model_name='bill',
            name='dealer_games',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer.dealergame'),
        ),
    ]
