# Generated by Django 4.2.7 on 2023-12-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_winning_commission_admin_and_more'),
        ('agent', '0009_bill_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('super', models.IntegerField()),
                ('box', models.IntegerField()),
                ('ab', models.IntegerField()),
                ('bc', models.IntegerField()),
                ('ac', models.IntegerField()),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.playtime')),
            ],
        ),
    ]
