# Generated by Django 4.2.5 on 2023-10-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_delete_dealerbill'),
        ('agent', '0009_bill_agent_games_bill_dealer_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='agent_games',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='dealer_games',
        ),
        migrations.AddField(
            model_name='bill',
            name='agent_games',
            field=models.ManyToManyField(to='agent.agentgame'),
        ),
        migrations.AddField(
            model_name='bill',
            name='dealer_games',
            field=models.ManyToManyField(to='dealer.dealergame'),
        ),
    ]
