# Generated by Django 4.2.7 on 2023-12-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_remove_gamecount_a_remove_gamecount_ab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='GameCount',
        ),
    ]
