# Generated by Django 4.2.7 on 2023-12-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_alter_bill_customer_delete_gamecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='customer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
