# Generated by Django 4.2.7 on 2023-12-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0013_alter_bill_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentgame',
            name='customer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentgametest',
            name='customer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
