# Generated by Django 4.2.5 on 2023-10-22 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealer', '0001_initial'),
        ('website', '0001_initial'),
        ('adminapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealergametest',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.agent'),
        ),
        migrations.AddField(
            model_name='dealergametest',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.dealer'),
        ),
        migrations.AddField(
            model_name='dealergametest',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.playtime'),
        ),
        migrations.AddField(
            model_name='dealergame',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.agent'),
        ),
        migrations.AddField(
            model_name='dealergame',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.dealer'),
        ),
        migrations.AddField(
            model_name='dealergame',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.playtime'),
        ),
    ]
