# Generated by Django 4.2.7 on 2023-11-12 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_agent_agent_name_alter_agent_phone_number_and_more'),
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealergametest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.agent'),
        ),
        migrations.AlterField(
            model_name='dealergametest',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_dealergametests', to='website.agent'),
        ),
    ]
