# Generated by Django 4.2.5 on 2023-10-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealergame',
            name='combined',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
