# Generated by Django 4.2.7 on 2023-11-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_agent_agent_name_alter_agent_phone_number_and_more'),
        ('adminapp', '0003_blockednumber_time'),
        ('dealer', '0002_dealergametest_created_by_alter_dealergametest_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerGameAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('LSK', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('d_amount', models.FloatField()),
                ('c_amount', models.FloatField()),
                ('combined', models.BooleanField()),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.agent')),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.dealer')),
                ('dealer_game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealergame')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.playtime')),
            ],
        ),
    ]
