# Generated by Django 4.2.5 on 2023-10-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_dealerbill_agent_dealergame_agent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DealerBill',
        ),
    ]
