# Generated by Django 4.2.7 on 2023-11-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_dealergametestadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealergameadmin',
            name='dealer_game',
        ),
        migrations.AddField(
            model_name='dealergameadmin',
            name='dealer_game',
            field=models.ManyToManyField(to='dealer.dealergame'),
        ),
    ]
