# Generated by Django 4.2.7 on 2023-11-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0006_remove_dealergametestadmin_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealergame',
            name='count_admin',
        ),
        migrations.RemoveField(
            model_name='dealergametest',
            name='count_admin',
        ),
    ]
