# Generated by Django 4.2.7 on 2023-11-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0007_remove_dealergame_count_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealergame',
            name='customer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealergametest',
            name='customer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
